import { staticBaseUrl } from "../../network/static";

export const logos = [
  `${staticBaseUrl}flutterwave-sponsor-logo.webp`,
  `${staticBaseUrl}baba-Ijebu.svg`,
  `${staticBaseUrl}magic-line.webp`,
  `${staticBaseUrl}pepsi.svg`,
  `${staticBaseUrl}road-14.webp`,
  "https://res.cloudinary.com/dqcy1vg4m/image/upload/v1670179267/2022/images/starradler.webp",
  "https://res.cloudinary.com/dqcy1vg4m/image/upload/v1670178547/2022/images/heineken.webp",
  `${staticBaseUrl}desperadoss.webp`,
  `${staticBaseUrl}flutterwave-sponsor-logo.webp`,
  `${staticBaseUrl}baba-Ijebu.svg`,
  `${staticBaseUrl}magic-line.webp`,
  `${staticBaseUrl}pepsi.svg`,
  `${staticBaseUrl}road-14.webp`,
  "https://res.cloudinary.com/dqcy1vg4m/image/upload/v1670179267/2022/images/starradler.webp",
  "https://res.cloudinary.com/dqcy1vg4m/image/upload/v1670178547/2022/images/heineken.webp",
  `${staticBaseUrl}desperadoss.webp`,
  `${staticBaseUrl}flutterwave-sponsor-logo.webp`,
  `${staticBaseUrl}baba-Ijebu.svg`,
  `${staticBaseUrl}magic-line.webp`,
  `${staticBaseUrl}pepsi.svg`,
  `${staticBaseUrl}road-14.webp`,
  "https://res.cloudinary.com/dqcy1vg4m/image/upload/v1670179267/2022/images/starradler.webp",
  "https://res.cloudinary.com/dqcy1vg4m/image/upload/v1670178547/2022/images/heineken.webp",
  `${staticBaseUrl}desperadoss.webp`,
  `${staticBaseUrl}flutterwave-sponsor-logo.webp`,
  `${staticBaseUrl}baba-Ijebu.svg`,
  `${staticBaseUrl}magic-line.webp`,
  `${staticBaseUrl}pepsi.svg`,
  `${staticBaseUrl}road-14.webp`,
  "https://res.cloudinary.com/dqcy1vg4m/image/upload/v1670179267/2022/images/starradler.webp",
  "https://res.cloudinary.com/dqcy1vg4m/image/upload/v1670178547/2022/images/heineken.webp",
  `${staticBaseUrl}desperadoss.webp`,
];

export const lineupDays = [
  {
    day: "1",
    date: "DEC 21",
    activity: "RHYTHM UNPLUGGED",
  },
  {
    day: "2",
    date: "DEC 22",
    activity: "MR. MONEY WITH THE VIBE -",
    feat: "ASAKE",
  },
  {
    day: "3",
    date: "DEC 23",
    activity: "MR. MONEY WITH THE VIBE 2 -",
    feat: "ASAKE",
  },
  {
    day: "4",
    date: "DEC 24",
    activity: "STARBOY LIVE -",
    feat: "WIZKID",
  },
  {
    day: "1",
    date: "DEC 21",
    activity: "RHYTHM UNPLUGGED",
  },
  {
    day: "2",
    date: "DEC 22",
    activity: "MR. MONEY WITH THE VIBE -",
    feat: "ASAKE",
  },
  {
    day: "3",
    date: "DEC 23",
    activity: "MR. MONEY WITH THE VIBE 2 -",
    feat: "ASAKE",
  },
  {
    day: "4",
    date: "DEC 24",
    activity: "STARBOY LIVE -",
    feat: "WIZKID",
  },
  {
    day: "1",
    date: "DEC 21",
    activity: "RHYTHM UNPLUGGED",
  },
  {
    day: "2",
    date: "DEC 22",
    activity: "MR. MONEY WITH THE VIBE -",
    feat: "ASAKE",
  },
  {
    day: "3",
    date: "DEC 23",
    activity: "MR. MONEY WITH THE VIBE 2 -",
    feat: "ASAKE",
  },
  {
    day: "4",
    date: "DEC 24",
    activity: "STARBOY LIVE -",
    feat: "WIZKID",
  },
  {
    day: "1",
    date: "DEC 21",
    activity: "RHYTHM UNPLUGGED",
  },
  {
    day: "2",
    date: "DEC 22",
    activity: "MR. MONEY WITH THE VIBE -",
    feat: "ASAKE",
  },
  {
    day: "3",
    date: "DEC 23",
    activity: "MR. MONEY WITH THE VIBE 2 -",
    feat: "ASAKE",
  },
  {
    day: "4",
    date: "DEC 24",
    activity: "STARBOY LIVE -",
    feat: "WIZKID",
  },
  {
    day: "1",
    date: "DEC 21",
    activity: "RHYTHM UNPLUGGED",
  },
  {
    day: "2",
    date: "DEC 22",
    activity: "MR. MONEY WITH THE VIBE -",
    feat: "ASAKE",
  },
  {
    day: "3",
    date: "DEC 23",
    activity: "MR. MONEY WITH THE VIBE 2 -",
    feat: "ASAKE",
  },
  {
    day: "4",
    date: "DEC 24",
    activity: "STARBOY LIVE -",
    feat: "WIZKID",
  },
  {
    day: "1",
    date: "DEC 21",
    activity: "RHYTHM UNPLUGGED",
  },
  {
    day: "2",
    date: "DEC 22",
    activity: "MR. MONEY WITH THE VIBE -",
    feat: "ASAKE",
  },
  {
    day: "3",
    date: "DEC 23",
    activity: "MR. MONEY WITH THE VIBE 2 -",
    feat: "ASAKE",
  },
  {
    day: "4",
    date: "DEC 24",
    activity: "STARBOY LIVE -",
    feat: "WIZKID",
  },
  {
    day: "1",
    date: "DEC 21",
    activity: "RHYTHM UNPLUGGED",
  },
  {
    day: "2",
    date: "DEC 22",
    activity: "MR. MONEY WITH THE VIBE -",
    feat: "ASAKE",
  },
  {
    day: "3",
    date: "DEC 23",
    activity: "MR. MONEY WITH THE VIBE 2 -",
    feat: "ASAKE",
  },
  {
    day: "4",
    date: "DEC 24",
    activity: "STARBOY LIVE -",
    feat: "WIZKID",
  },
  {
    day: "1",
    date: "DEC 21",
    activity: "RHYTHM UNPLUGGED",
  },
  {
    day: "2",
    date: "DEC 22",
    activity: "MR. MONEY WITH THE VIBE -",
    feat: "ASAKE",
  },
  {
    day: "3",
    date: "DEC 23",
    activity: "MR. MONEY WITH THE VIBE 2 -",
    feat: "ASAKE",
  },
  {
    day: "4",
    date: "DEC 24",
    activity: "STARBOY LIVE -",
    feat: "WIZKID",
  },
  {
    day: "1",
    date: "DEC 21",
    activity: "RHYTHM UNPLUGGED",
  },
  {
    day: "2",
    date: "DEC 22",
    activity: "MR. MONEY WITH THE VIBE -",
    feat: "ASAKE",
  },
  {
    day: "3",
    date: "DEC 23",
    activity: "MR. MONEY WITH THE VIBE 2 -",
    feat: "ASAKE",
  },
  {
    day: "4",
    date: "DEC 24",
    activity: "STARBOY LIVE -",
    feat: "WIZKID",
  },
  {
    day: "1",
    date: "DEC 21",
    activity: "RHYTHM UNPLUGGED",
  },
  {
    day: "2",
    date: "DEC 22",
    activity: "MR. MONEY WITH THE VIBE -",
    feat: "ASAKE",
  },
  {
    day: "3",
    date: "DEC 23",
    activity: "MR. MONEY WITH THE VIBE 2 -",
    feat: "ASAKE",
  },
  {
    day: "4",
    date: "DEC 24",
    activity: "STARBOY LIVE -",
    feat: "WIZKID",
  },
  {
    day: "1",
    date: "DEC 21",
    activity: "RHYTHM UNPLUGGED",
  },
  {
    day: "2",
    date: "DEC 22",
    activity: "MR. MONEY WITH THE VIBE -",
    feat: "ASAKE",
  },
  {
    day: "3",
    date: "DEC 23",
    activity: "MR. MONEY WITH THE VIBE 2 -",
    feat: "ASAKE",
  },
  {
    day: "4",
    date: "DEC 24",
    activity: "STARBOY LIVE -",
    feat: "WIZKID",
  },
  {
    day: "1",
    date: "DEC 21",
    activity: "RHYTHM UNPLUGGED",
  },
  {
    day: "2",
    date: "DEC 22",
    activity: "MR. MONEY WITH THE VIBE -",
    feat: "ASAKE",
  },
  {
    day: "3",
    date: "DEC 23",
    activity: "MR. MONEY WITH THE VIBE 2 -",
    feat: "ASAKE",
  },
  {
    day: "4",
    date: "DEC 24",
    activity: "STARBOY LIVE -",
    feat: "WIZKID",
  },
  {
    day: "1",
    date: "DEC 21",
    activity: "RHYTHM UNPLUGGED",
  },
  {
    day: "2",
    date: "DEC 22",
    activity: "MR. MONEY WITH THE VIBE -",
    feat: "ASAKE",
  },
  {
    day: "3",
    date: "DEC 23",
    activity: "MR. MONEY WITH THE VIBE 2 -",
    feat: "ASAKE",
  },
  {
    day: "4",
    date: "DEC 24",
    activity: "STARBOY LIVE -",
    feat: "WIZKID",
  },
  {
    day: "1",
    date: "DEC 21",
    activity: "RHYTHM UNPLUGGED",
  },
  {
    day: "2",
    date: "DEC 22",
    activity: "MR. MONEY WITH THE VIBE -",
    feat: "ASAKE",
  },
  {
    day: "3",
    date: "DEC 23",
    activity: "MR. MONEY WITH THE VIBE 2 -",
    feat: "ASAKE",
  },
  {
    day: "4",
    date: "DEC 24",
    activity: "STARBOY LIVE -",
    feat: "WIZKID",
  },
  {
    day: "1",
    date: "DEC 21",
    activity: "RHYTHM UNPLUGGED",
  },
  {
    day: "2",
    date: "DEC 22",
    activity: "MR. MONEY WITH THE VIBE -",
    feat: "ASAKE",
  },
  {
    day: "3",
    date: "DEC 23",
    activity: "MR. MONEY WITH THE VIBE 2 -",
    feat: "ASAKE",
  },
  {
    day: "4",
    date: "DEC 24",
    activity: "STARBOY LIVE -",
    feat: "WIZKID",
  },
  {
    day: "1",
    date: "DEC 21",
    activity: "RHYTHM UNPLUGGED",
  },
  {
    day: "2",
    date: "DEC 22",
    activity: "MR. MONEY WITH THE VIBE -",
    feat: "ASAKE",
  },
  {
    day: "3",
    date: "DEC 23",
    activity: "MR. MONEY WITH THE VIBE 2 -",
    feat: "ASAKE",
  },
  {
    day: "4",
    date: "DEC 24",
    activity: "STARBOY LIVE -",
    feat: "WIZKID",
  },
  {
    day: "1",
    date: "DEC 21",
    activity: "RHYTHM UNPLUGGED",
  },
  {
    day: "2",
    date: "DEC 22",
    activity: "MR. MONEY WITH THE VIBE -",
    feat: "ASAKE",
  },
  {
    day: "3",
    date: "DEC 23",
    activity: "MR. MONEY WITH THE VIBE 2 -",
    feat: "ASAKE",
  },
  {
    day: "4",
    date: "DEC 24",
    activity: "STARBOY LIVE -",
    feat: "WIZKID",
  },
  {
    day: "1",
    date: "DEC 21",
    activity: "RHYTHM UNPLUGGED",
  },
  {
    day: "2",
    date: "DEC 22",
    activity: "MR. MONEY WITH THE VIBE -",
    feat: "ASAKE",
  },
  {
    day: "3",
    date: "DEC 23",
    activity: "MR. MONEY WITH THE VIBE 2 -",
    feat: "ASAKE",
  },
  {
    day: "4",
    date: "DEC 24",
    activity: "STARBOY LIVE -",
    feat: "WIZKID",
  },
  {
    day: "1",
    date: "DEC 21",
    activity: "RHYTHM UNPLUGGED",
  },
  {
    day: "2",
    date: "DEC 22",
    activity: "MR. MONEY WITH THE VIBE -",
    feat: "ASAKE",
  },
  {
    day: "3",
    date: "DEC 23",
    activity: "MR. MONEY WITH THE VIBE 2 -",
    feat: "ASAKE",
  },
  {
    day: "4",
    date: "DEC 24",
    activity: "STARBOY LIVE -",
    feat: "WIZKID",
  },
  {
    day: "1",
    date: "DEC 21",
    activity: "RHYTHM UNPLUGGED",
  },
  {
    day: "2",
    date: "DEC 22",
    activity: "MR. MONEY WITH THE VIBE -",
    feat: "ASAKE",
  },
  {
    day: "3",
    date: "DEC 23",
    activity: "MR. MONEY WITH THE VIBE 2 -",
    feat: "ASAKE",
  },
  {
    day: "4",
    date: "DEC 24",
    activity: "STARBOY LIVE -",
    feat: "WIZKID",
  },
  {
    day: "1",
    date: "DEC 21",
    activity: "RHYTHM UNPLUGGED",
  },
  {
    day: "2",
    date: "DEC 22",
    activity: "MR. MONEY WITH THE VIBE -",
    feat: "ASAKE",
  },
  {
    day: "3",
    date: "DEC 23",
    activity: "MR. MONEY WITH THE VIBE 2 -",
    feat: "ASAKE",
  },
  {
    day: "4",
    date: "DEC 24",
    activity: "STARBOY LIVE -",
    feat: "WIZKID",
  },
  {
    day: "1",
    date: "DEC 21",
    activity: "RHYTHM UNPLUGGED",
  },
  {
    day: "2",
    date: "DEC 22",
    activity: "MR. MONEY WITH THE VIBE -",
    feat: "ASAKE",
  },
  {
    day: "3",
    date: "DEC 23",
    activity: "MR. MONEY WITH THE VIBE 2 -",
    feat: "ASAKE",
  },
  {
    day: "4",
    date: "DEC 24",
    activity: "STARBOY LIVE -",
    feat: "WIZKID",
  },
  {
    day: "1",
    date: "DEC 21",
    activity: "RHYTHM UNPLUGGED",
  },
  {
    day: "2",
    date: "DEC 22",
    activity: "MR. MONEY WITH THE VIBE -",
    feat: "ASAKE",
  },
  {
    day: "3",
    date: "DEC 23",
    activity: "MR. MONEY WITH THE VIBE 2 -",
    feat: "ASAKE",
  },
  {
    day: "4",
    date: "DEC 24",
    activity: "STARBOY LIVE -",
    feat: "WIZKID",
  },
  {
    day: "1",
    date: "DEC 21",
    activity: "RHYTHM UNPLUGGED",
  },
  {
    day: "2",
    date: "DEC 22",
    activity: "MR. MONEY WITH THE VIBE -",
    feat: "ASAKE",
  },
  {
    day: "3",
    date: "DEC 23",
    activity: "MR. MONEY WITH THE VIBE 2 -",
    feat: "ASAKE",
  },
  {
    day: "4",
    date: "DEC 24",
    activity: "STARBOY LIVE -",
    feat: "WIZKID",
  },
  {
    day: "1",
    date: "DEC 21",
    activity: "RHYTHM UNPLUGGED",
  },
  {
    day: "2",
    date: "DEC 22",
    activity: "MR. MONEY WITH THE VIBE -",
    feat: "ASAKE",
  },
  {
    day: "3",
    date: "DEC 23",
    activity: "MR. MONEY WITH THE VIBE 2 -",
    feat: "ASAKE",
  },
  {
    day: "4",
    date: "DEC 24",
    activity: "STARBOY LIVE -",
    feat: "WIZKID",
  },
  {
    day: "1",
    date: "DEC 21",
    activity: "RHYTHM UNPLUGGED",
  },
  {
    day: "2",
    date: "DEC 22",
    activity: "MR. MONEY WITH THE VIBE -",
    feat: "ASAKE",
  },
  {
    day: "3",
    date: "DEC 23",
    activity: "MR. MONEY WITH THE VIBE 2 -",
    feat: "ASAKE",
  },
  {
    day: "4",
    date: "DEC 24",
    activity: "STARBOY LIVE -",
    feat: "WIZKID",
  },
  {
    day: "1",
    date: "DEC 21",
    activity: "RHYTHM UNPLUGGED",
  },
  {
    day: "2",
    date: "DEC 22",
    activity: "MR. MONEY WITH THE VIBE -",
    feat: "ASAKE",
  },
  {
    day: "3",
    date: "DEC 23",
    activity: "MR. MONEY WITH THE VIBE 2 -",
    feat: "ASAKE",
  },
  {
    day: "4",
    date: "DEC 24",
    activity: "STARBOY LIVE -",
    feat: "WIZKID",
  },
  {
    day: "1",
    date: "DEC 21",
    activity: "RHYTHM UNPLUGGED",
  },
  {
    day: "2",
    date: "DEC 22",
    activity: "MR. MONEY WITH THE VIBE -",
    feat: "ASAKE",
  },
  {
    day: "3",
    date: "DEC 23",
    activity: "MR. MONEY WITH THE VIBE 2 -",
    feat: "ASAKE",
  },
  {
    day: "4",
    date: "DEC 24",
    activity: "STARBOY LIVE -",
    feat: "WIZKID",
  },
  {
    day: "1",
    date: "DEC 21",
    activity: "RHYTHM UNPLUGGED",
  },
  {
    day: "2",
    date: "DEC 22",
    activity: "MR. MONEY WITH THE VIBE -",
    feat: "ASAKE",
  },
  {
    day: "3",
    date: "DEC 23",
    activity: "MR. MONEY WITH THE VIBE 2 -",
    feat: "ASAKE",
  },
  {
    day: "4",
    date: "DEC 24",
    activity: "STARBOY LIVE -",
    feat: "WIZKID",
  },
  {
    day: "1",
    date: "DEC 21",
    activity: "RHYTHM UNPLUGGED",
  },
  {
    day: "2",
    date: "DEC 22",
    activity: "MR. MONEY WITH THE VIBE -",
    feat: "ASAKE",
  },
  {
    day: "3",
    date: "DEC 23",
    activity: "MR. MONEY WITH THE VIBE 2 -",
    feat: "ASAKE",
  },
  {
    day: "4",
    date: "DEC 24",
    activity: "STARBOY LIVE -",
    feat: "WIZKID",
  },
  {
    day: "1",
    date: "DEC 21",
    activity: "RHYTHM UNPLUGGED",
  },
  {
    day: "2",
    date: "DEC 22",
    activity: "MR. MONEY WITH THE VIBE -",
    feat: "ASAKE",
  },
  {
    day: "3",
    date: "DEC 23",
    activity: "MR. MONEY WITH THE VIBE 2 -",
    feat: "ASAKE",
  },
  {
    day: "4",
    date: "DEC 24",
    activity: "STARBOY LIVE -",
    feat: "WIZKID",
  },
  {
    day: "1",
    date: "DEC 21",
    activity: "RHYTHM UNPLUGGED",
  },
  {
    day: "2",
    date: "DEC 22",
    activity: "MR. MONEY WITH THE VIBE -",
    feat: "ASAKE",
  },
  {
    day: "3",
    date: "DEC 23",
    activity: "MR. MONEY WITH THE VIBE 2 -",
    feat: "ASAKE",
  },
  {
    day: "4",
    date: "DEC 24",
    activity: "STARBOY LIVE -",
    feat: "WIZKID",
  },
  {
    day: "1",
    date: "DEC 21",
    activity: "RHYTHM UNPLUGGED",
  },
  {
    day: "2",
    date: "DEC 22",
    activity: "MR. MONEY WITH THE VIBE -",
    feat: "ASAKE",
  },
  {
    day: "3",
    date: "DEC 23",
    activity: "MR. MONEY WITH THE VIBE 2 -",
    feat: "ASAKE",
  },
  {
    day: "4",
    date: "DEC 24",
    activity: "STARBOY LIVE -",
    feat: "WIZKID",
  },
  {
    day: "1",
    date: "DEC 21",
    activity: "RHYTHM UNPLUGGED",
  },
  {
    day: "2",
    date: "DEC 22",
    activity: "MR. MONEY WITH THE VIBE -",
    feat: "ASAKE",
  },
  {
    day: "3",
    date: "DEC 23",
    activity: "MR. MONEY WITH THE VIBE 2 -",
    feat: "ASAKE",
  },
  {
    day: "4",
    date: "DEC 24",
    activity: "STARBOY LIVE -",
    feat: "WIZKID",
  },
  {
    day: "1",
    date: "DEC 21",
    activity: "RHYTHM UNPLUGGED",
  },
  {
    day: "2",
    date: "DEC 22",
    activity: "MR. MONEY WITH THE VIBE -",
    feat: "ASAKE",
  },
  {
    day: "3",
    date: "DEC 23",
    activity: "MR. MONEY WITH THE VIBE 2 -",
    feat: "ASAKE",
  },
  {
    day: "4",
    date: "DEC 24",
    activity: "STARBOY LIVE -",
    feat: "WIZKID",
  },
  {
    day: "1",
    date: "DEC 21",
    activity: "RHYTHM UNPLUGGED",
  },
  {
    day: "2",
    date: "DEC 22",
    activity: "MR. MONEY WITH THE VIBE -",
    feat: "ASAKE",
  },
  {
    day: "3",
    date: "DEC 23",
    activity: "MR. MONEY WITH THE VIBE 2 -",
    feat: "ASAKE",
  },
  {
    day: "4",
    date: "DEC 24",
    activity: "STARBOY LIVE -",
    feat: "WIZKID",
  },
];
