export const ruleList = [
  "Festival tickets for Flutterwave Flytime Fest 2022 are sold by Flutterwave Flytime Fest on the website and all necessary info will be sent via email. This way, we ensure that no unwanted brokering can occur and that all fans have an equal chance of attending the festival for the price set by the organizer.",
  " Upon showing your ticket, you will receive a festival wristband at the entrance. This wristband must be worn on your wrist. Wristbands will be given each day for the festival. Straps that are not on your wrist are not valid, and they may not change owner. When illegality is discovered, for example, fake tickets, fraud with wristbands, or climbing over fences, access will be denied, and the police will be informed. You are responsible for your ticket and wristband.",
  "It’s forbidden to carry illegal substances on you or to deal in drugs at Flutterwave Flytime Fest 2022. There will be checks at the festival entrance. If our staff finds large substances of illegal drugs you can be removed from the festival site and/or be transferred to the local authorities.",
  "Do not tamper, stretch, cut or alter your wristband in any way. Altered wristbands will be invalid and the bearer will be subject to eviction from the festival grounds.",
  " Professional photographic, film, and sound equipment may not be taken onto the premises. Professional equipment includes, for example, cameras with interchangeable lenses and reflex cameras. Video cameras, camcorders, and other (sound) recording equipment are not allowed. The judgment of whether professional equipment is used is solely up to the organization of Flutterwave Flytime Fest. Flutterwave Flytime Fest will confiscate illegally obtained recordings! Cell phones with photo and video capabilities and simple digital cameras are allowed.",
  "Food, (soft) drinks, water bottles, doppers, and similar hard plastic bottles are not allowed at Flutterwave Flytime Fest.",
  "Flutterwave Flytime Fest is not responsible for lost or stolen belongings. Ensure to take care of your belongings!",

  "Visitors agree to be photographed, filmed or recorded as part of Flutterwave Flytime Fest 2022 audience. All video, photo and audio materials acquired on festival sites are subject to be used in promotional materials for the festival without any limitations of time and space.",
  "Distribution of flyers or posters during the festival or on festival grounds, is not allowed. If you want to promote your event or product please contact the Organiser who can give you the possibility to place an advertisement on the festival grounds. Promotional activities without the written permission of the Organiser will be legally persecuted. ",
  "Pets are not allowed at the Festival.",
];
